Configurable project name
benchkram/bob pull request #44
Opened 2022-04-01 11:28 UTC by rdnt

- If empty, set project name based on the project's absolute filesystem path
- Validate uniqueness of project name across aggregated bobfiles
- Project name passed to tasks, so that artifacts can be properly stored if needed (e.g. in a remote store)

2022-04-01 11:42 UTC, Equanox commented
Closes #12

2022-04-06 14:27 UTC, Equanox requested changes

2022-04-08 10:55 UTC, rdnt commented
@Equanox regarding `TODO: maybe don't leak absolute path of environment` (bob/aggregate.go:108):

Since we will not be syncing projects without a proper remote set up as a project name, there is no possibility to have an absolute path in the remote artifact's metadata. Let me know if I should remove the comment from the code.

2022-04-08 12:28 UTC, Equanox commented
@rdnt yes that can be unexpected.. let's keep an eye on it.. though it seems to be save for now.

2022-04-08 13:37 UTC, Equanox approved these changes

2022-04-08 13:41 UTC, merged